### ISSUE TITLE
Unclear ID

### ISSUE THREAD

**Issue by choisy** [ecomore2/gps#11]
Somphavanh: in the file `raw-data/GPS/all main data.xls`, tab `IPL server`, cell `34B`, the ID of the sample is not clear. Can you please correct it?
Thanks, Marc.

**Comment by somphavanh** [comment]
for cell 34B ,the district hospital send the gps for us , but we didn't receive this patient, so we can delete it

**Comment by choisy** [comment]
Done. Thanks.
