### ISSUE TITLE
Wrong latitudes for 3459, 3460, 3648 and 3698

### ISSUE THREAD

**Issue by choisy** [ecomore2/gps#13]
Somphavanh: in the `raw_data/GPS/all main data.xls` file, `new machine` tab, the latitude of ID `3459` (line 110), `3460` (line 111), `3648` (line 109) and `3698` (line 115) are equal to their longitude. Can you correct this please?
Thanks, Marc.

**Comment by somphavanh** [comment]
i have already corrected , please find at the  file all main data-2018-9-27  in dropbox .

**Comment by choisy** [comment]
Amazing! Thanks a lot!
Marc.
