### ISSUE TITLE
Identical longitude and latitude

### ISSUE THREAD

**Issue by choisy** [ecomore2/gps#5]
There are 32 points that have identical latitude and longitude. Their ID are 3601, 3605, 3607, 3608, 3643, 3648, 3684, 3692, 3694, 3720, 3760, 3762, 3767, 3769, 3770, 3771, 3779, 3780, 3781, 3782, 3786, 3796, 3797, 3799, 3801, 3802, 3831, 3855, 3872, 3908, 3925 and 3944. It seems that the latitudes are incorrectly equal to the longitudes here. Can it be corrected?

**Comment by somphavanh** [comment]
i have already corrected it , i will send you the new one
